import Head from "next/head";

import NavigationBar from "@/components/NavigationBar";
import Hero from "@/components/Hero";
import Recipe from "@/components/recipe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home chef recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Serif:wght@400;700&family=Roboto:wght@100;300;500;700&family=Ysabeau+SC:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <NavigationBar />
      <Hero />

      <Recipe />
      <div className="add_recipe_button">
        <div className="add_recipe_text">
          <a href="/add-recipe">
            Add <br></br>New <br></br> Recipe
          </a>
        </div>
      </div>
    </>
  );
}
