import Head from "next/head";

import NavigationBar from "@/components/NavigationBar";
import Hero from "@/components/Hero";
import Recipe from "@/components/recipe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home chef recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <Hero />

      <button>
        <a href="/add-recipe">Add Recipe</a>
      </button>

      <Recipe />
    </>
  );
}
